/*
 * Copyright (c) 2018 Open Source Foundries Ltd.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#define MDM_UART_DEV_NAME		CONFIG_UART_MCUX_2_NAME

static const struct mdm_control_pinconfig pinconfig[] = {
	/* MDM_BOOT_MODE_SEL */
	PINCONFIG(CONFIG_GPIO_MCUX_PORTC_NAME, 17),
	/* MDM_POWER */
	PINCONFIG(CONFIG_GPIO_MCUX_PORTB_NAME, 9),
	/* MDM_KEEP_AWAKE */
	PINCONFIG(CONFIG_GPIO_MCUX_PORTC_NAME, 2),
	/* MDM_RESET */
	PINCONFIG(CONFIG_GPIO_MCUX_PORTC_NAME, 12),
	/* SHLD_3V3_1V8_SIG_TRANS_ENA */
	PINCONFIG(CONFIG_GPIO_MCUX_PORTC_NAME, 4),
	/* MDM_SEND_OK */
	PINCONFIG(CONFIG_GPIO_MCUX_PORTD_NAME, 0),
};
